import type { Metadata } from "next";
import Loading from "./loading";
import { Suspense } from "react";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
       <Suspense fallback={<Loading/>}>
      <body
        
      >
        {children}
      </body>
      </Suspense>
    </html>
  
  );
}
